groupings:
  - name: pod
    members_per_group: 2
  - name: rack
    members_per_group: 1

gpu_nodes:
  total_nodes: 2
  fabric_port_layouts:
    backend:
      base_lane_bandwidth_gb: 100
      total_lane_units: 1
      supported_port_modes:
        - port_bandwidth_gb: 100
          lane_units: 1
    frontend:
      base_lane_bandwidth_gb: 50
      total_lane_units: 1
      supported_port_modes:
        - port_bandwidth_gb: 50
          lane_units: 1
    oob:
      base_lane_bandwidth_gb: 25
      total_lane_units: 1
      supported_port_modes:
        - port_bandwidth_gb: 25
          lane_units: 1

fabrics:
  - name: backend
    grouping: pod
    layers:
      - name: leaf
        placement: group
        nodes_per_group: 1
        port_layout:
          base_lane_bandwidth_gb: 100
          total_lane_units: 3
          supported_port_modes:
            - port_bandwidth_gb: 100
              lane_units: 1
      - name: spine
        placement: global
        nodes_per_group: 1
        port_layout:
          base_lane_bandwidth_gb: 100
          total_lane_units: 1
          supported_port_modes:
            - port_bandwidth_gb: 100
              lane_units: 1
    links:
      - from: gpu_nodes
        to: leaf
        policy: within_group_full_mesh
        cables_per_pair: 1
        cable_bandwidth_gb: 100
      - from: leaf
        to: spine
        policy: group_to_global_full_mesh
        cables_per_pair: 1
        cable_bandwidth_gb: 100

  - name: frontend
    grouping: pod
    layers:
      - name: tor
        placement: group
        nodes_per_group: 1
        port_layout:
          base_lane_bandwidth_gb: 50
          total_lane_units: 2
          supported_port_modes:
            - port_bandwidth_gb: 50
              lane_units: 1
    links:
      - from: gpu_nodes
        to: tor
        policy: within_group_full_mesh
        cables_per_pair: 1
        cable_bandwidth_gb: 50

  - name: oob
    grouping: rack
    layers:
      - name: mgmt
        placement: global
        nodes_per_group: 1
        port_layout:
          base_lane_bandwidth_gb: 25
          total_lane_units: 2
          supported_port_modes:
            - port_bandwidth_gb: 25
              lane_units: 1
    links:
      - from: gpu_nodes
        to: mgmt
        policy: group_to_global_full_mesh
        cables_per_pair: 1
        cable_bandwidth_gb: 25
