layers:
  - name: compute
    node_count_in_layer: 32
    ports_per_node: 8
    port_bandwidth_gb_per_port: 400
    uplink_cables_per_node_to_each_node_in_next_layer: 1
    uplink_cable_bandwidth_gb: 400
  - name: aggregation
    node_count_in_layer: 8
    ports_per_node: 36
    port_bandwidth_gb_per_port: 800
    downlink_cables_per_node_to_each_node_in_previous_layer: 1
    downlink_cable_bandwidth_gb: 400
    uplink_cables_per_node_to_each_node_in_next_layer: 2
    uplink_cable_bandwidth_gb: 800
  - name: fabric
    node_count_in_layer: 4
    ports_per_node: 20
    port_bandwidth_gb_per_port: 800
    downlink_cables_per_node_to_each_node_in_previous_layer: 2
    downlink_cable_bandwidth_gb: 800
    uplink_cables_per_node_to_each_node_in_next_layer: 2
    uplink_cable_bandwidth_gb: 800
  - name: backbone
    node_count_in_layer: 2
    ports_per_node: 8
    port_bandwidth_gb_per_port: 800
    downlink_cables_per_node_to_each_node_in_previous_layer: 2
    downlink_cable_bandwidth_gb: 800
